// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GPDataTypes.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GPDataTypes.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace fi {
namespace aalto {
namespace ssg {
namespace opentee {
namespace imps {
namespace pbdatatypes {

namespace {

const ::google::protobuf::Descriptor* TeecOperation_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TeecOperation_reflection_ = NULL;
const ::google::protobuf::Descriptor* TeecParameter_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TeecParameter_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* TeecParameter_Type_descriptor_ = NULL;
const ::google::protobuf::Descriptor* TeecSharedMemory_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TeecSharedMemory_reflection_ = NULL;
const ::google::protobuf::Descriptor* TeecSharedMemoryReference_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TeecSharedMemoryReference_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* TeecSharedMemoryReference_Flag_descriptor_ = NULL;
const ::google::protobuf::Descriptor* TeecValue_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TeecValue_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* TeecValue_Flag_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_GPDataTypes_2eproto() {
  protobuf_AddDesc_GPDataTypes_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "GPDataTypes.proto");
  GOOGLE_CHECK(file != NULL);
  TeecOperation_descriptor_ = file->message_type(0);
  static const int TeecOperation_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecOperation, mstarted_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecOperation, mparams_),
  };
  TeecOperation_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TeecOperation_descriptor_,
      TeecOperation::default_instance_,
      TeecOperation_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecOperation, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecOperation, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TeecOperation));
  TeecParameter_descriptor_ = file->message_type(1);
  static const int TeecParameter_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecParameter, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecParameter, teecsharedmemoryreference_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecParameter, teecvalue_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecParameter, placeholder_),
  };
  TeecParameter_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TeecParameter_descriptor_,
      TeecParameter::default_instance_,
      TeecParameter_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecParameter, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecParameter, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TeecParameter));
  TeecParameter_Type_descriptor_ = TeecParameter_descriptor_->enum_type(0);
  TeecSharedMemory_descriptor_ = file->message_type(2);
  static const int TeecSharedMemory_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecSharedMemory, mbuffer_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecSharedMemory, mflag_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecSharedMemory, size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecSharedMemory, mreturnsize_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecSharedMemory, mid_),
  };
  TeecSharedMemory_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TeecSharedMemory_descriptor_,
      TeecSharedMemory::default_instance_,
      TeecSharedMemory_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecSharedMemory, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecSharedMemory, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TeecSharedMemory));
  TeecSharedMemoryReference_descriptor_ = file->message_type(3);
  static const int TeecSharedMemoryReference_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecSharedMemoryReference, parent_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecSharedMemoryReference, moffset_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecSharedMemoryReference, mflag_),
  };
  TeecSharedMemoryReference_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TeecSharedMemoryReference_descriptor_,
      TeecSharedMemoryReference::default_instance_,
      TeecSharedMemoryReference_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecSharedMemoryReference, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecSharedMemoryReference, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TeecSharedMemoryReference));
  TeecSharedMemoryReference_Flag_descriptor_ = TeecSharedMemoryReference_descriptor_->enum_type(0);
  TeecValue_descriptor_ = file->message_type(4);
  static const int TeecValue_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecValue, a_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecValue, b_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecValue, mflag_),
  };
  TeecValue_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TeecValue_descriptor_,
      TeecValue::default_instance_,
      TeecValue_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecValue, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TeecValue, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TeecValue));
  TeecValue_Flag_descriptor_ = TeecValue_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_GPDataTypes_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TeecOperation_descriptor_, &TeecOperation::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TeecParameter_descriptor_, &TeecParameter::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TeecSharedMemory_descriptor_, &TeecSharedMemory::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TeecSharedMemoryReference_descriptor_, &TeecSharedMemoryReference::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TeecValue_descriptor_, &TeecValue::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_GPDataTypes_2eproto() {
  delete TeecOperation::default_instance_;
  delete TeecOperation_reflection_;
  delete TeecParameter::default_instance_;
  delete TeecParameter_reflection_;
  delete TeecSharedMemory::default_instance_;
  delete TeecSharedMemory_reflection_;
  delete TeecSharedMemoryReference::default_instance_;
  delete TeecSharedMemoryReference_reflection_;
  delete TeecValue::default_instance_;
  delete TeecValue_reflection_;
}

void protobuf_AddDesc_GPDataTypes_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021GPDataTypes.proto\022%fi.aalto.ssg.opente"
    "e.imps.pbdatatypes\"h\n\rTeecOperation\022\020\n\010m"
    "Started\030\001 \002(\005\022E\n\007mParams\030\002 \003(\01324.fi.aalt"
    "o.ssg.opentee.imps.pbdatatypes.TeecParam"
    "eter\"\274\002\n\rTeecParameter\022G\n\004type\030\001 \002(\01629.f"
    "i.aalto.ssg.opentee.imps.pbdatatypes.Tee"
    "cParameter.Type\022c\n\031teecSharedMemoryRefer"
    "ence\030\002 \001(\0132@.fi.aalto.ssg.opentee.imps.p"
    "bdatatypes.TeecSharedMemoryReference\022C\n\t"
    "teecValue\030\003 \001(\01320.fi.aalto.ssg.opentee.i"
    "mps.pbdatatypes.TeecValue\022\023\n\013placeHolder"
    "\030\004 \001(\005\"#\n\004Type\022\007\n\003smr\020\001\022\007\n\003val\020\002\022\t\n\005empt"
    "y\020\003\"b\n\020TeecSharedMemory\022\017\n\007mBuffer\030\001 \002(\014"
    "\022\r\n\005mFlag\030\002 \002(\005\022\014\n\004size\030\003 \002(\005\022\023\n\013mReturn"
    "Size\030\004 \001(\005\022\013\n\003mID\030\005 \001(\005\"\231\002\n\031TeecSharedMe"
    "moryReference\022G\n\006parent\030\001 \002(\01327.fi.aalto"
    ".ssg.opentee.imps.pbdatatypes.TeecShared"
    "Memory\022\017\n\007mOffset\030\002 \002(\005\022T\n\005mFlag\030\003 \002(\0162E"
    ".fi.aalto.ssg.opentee.imps.pbdatatypes.T"
    "eecSharedMemoryReference.Flag\"L\n\004Flag\022\025\n"
    "\021TEEC_MEMREF_INPUT\020\r\022\026\n\022TEEC_MEMREF_OUTP"
    "UT\020\016\022\025\n\021TEEC_MEMREF_INOUT\020\017\"\262\001\n\tTeecValu"
    "e\022\t\n\001a\030\001 \002(\005\022\t\n\001b\030\002 \002(\005\022D\n\005mFlag\030\003 \002(\01625"
    ".fi.aalto.ssg.opentee.imps.pbdatatypes.T"
    "eecValue.Flag\"I\n\004Flag\022\024\n\020TEEC_VALUE_INPU"
    "T\020\001\022\025\n\021TEEC_VALUE_OUTPUT\020\002\022\024\n\020TEEC_VALUE"
    "_INOUT\020\003", 1048);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GPDataTypes.proto", &protobuf_RegisterTypes);
  TeecOperation::default_instance_ = new TeecOperation();
  TeecParameter::default_instance_ = new TeecParameter();
  TeecSharedMemory::default_instance_ = new TeecSharedMemory();
  TeecSharedMemoryReference::default_instance_ = new TeecSharedMemoryReference();
  TeecValue::default_instance_ = new TeecValue();
  TeecOperation::default_instance_->InitAsDefaultInstance();
  TeecParameter::default_instance_->InitAsDefaultInstance();
  TeecSharedMemory::default_instance_->InitAsDefaultInstance();
  TeecSharedMemoryReference::default_instance_->InitAsDefaultInstance();
  TeecValue::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_GPDataTypes_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_GPDataTypes_2eproto {
  StaticDescriptorInitializer_GPDataTypes_2eproto() {
    protobuf_AddDesc_GPDataTypes_2eproto();
  }
} static_descriptor_initializer_GPDataTypes_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int TeecOperation::kMStartedFieldNumber;
const int TeecOperation::kMParamsFieldNumber;
#endif  // !_MSC_VER

TeecOperation::TeecOperation()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecOperation)
}

void TeecOperation::InitAsDefaultInstance() {
}

TeecOperation::TeecOperation(const TeecOperation& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecOperation)
}

void TeecOperation::SharedCtor() {
  _cached_size_ = 0;
  mstarted_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TeecOperation::~TeecOperation() {
  // @@protoc_insertion_point(destructor:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecOperation)
  SharedDtor();
}

void TeecOperation::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TeecOperation::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TeecOperation::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TeecOperation_descriptor_;
}

const TeecOperation& TeecOperation::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GPDataTypes_2eproto();
  return *default_instance_;
}

TeecOperation* TeecOperation::default_instance_ = NULL;

TeecOperation* TeecOperation::New() const {
  return new TeecOperation;
}

void TeecOperation::Clear() {
  mstarted_ = 0;
  mparams_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TeecOperation::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecOperation)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 mStarted = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mstarted_)));
          set_has_mstarted();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_mParams;
        break;
      }

      // repeated .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter mParams = 2;
      case 2: {
        if (tag == 18) {
         parse_mParams:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_mparams()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_mParams;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecOperation)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecOperation)
  return false;
#undef DO_
}

void TeecOperation::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecOperation)
  // required int32 mStarted = 1;
  if (has_mstarted()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->mstarted(), output);
  }

  // repeated .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter mParams = 2;
  for (int i = 0; i < this->mparams_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->mparams(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecOperation)
}

::google::protobuf::uint8* TeecOperation::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecOperation)
  // required int32 mStarted = 1;
  if (has_mstarted()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->mstarted(), target);
  }

  // repeated .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter mParams = 2;
  for (int i = 0; i < this->mparams_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->mparams(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecOperation)
  return target;
}

int TeecOperation::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 mStarted = 1;
    if (has_mstarted()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->mstarted());
    }

  }
  // repeated .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter mParams = 2;
  total_size += 1 * this->mparams_size();
  for (int i = 0; i < this->mparams_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->mparams(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TeecOperation::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TeecOperation* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TeecOperation*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TeecOperation::MergeFrom(const TeecOperation& from) {
  GOOGLE_CHECK_NE(&from, this);
  mparams_.MergeFrom(from.mparams_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_mstarted()) {
      set_mstarted(from.mstarted());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TeecOperation::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TeecOperation::CopyFrom(const TeecOperation& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TeecOperation::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->mparams())) return false;
  return true;
}

void TeecOperation::Swap(TeecOperation* other) {
  if (other != this) {
    std::swap(mstarted_, other->mstarted_);
    mparams_.Swap(&other->mparams_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TeecOperation::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TeecOperation_descriptor_;
  metadata.reflection = TeecOperation_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* TeecParameter_Type_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TeecParameter_Type_descriptor_;
}
bool TeecParameter_Type_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const TeecParameter_Type TeecParameter::smr;
const TeecParameter_Type TeecParameter::val;
const TeecParameter_Type TeecParameter::empty;
const TeecParameter_Type TeecParameter::Type_MIN;
const TeecParameter_Type TeecParameter::Type_MAX;
const int TeecParameter::Type_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int TeecParameter::kTypeFieldNumber;
const int TeecParameter::kTeecSharedMemoryReferenceFieldNumber;
const int TeecParameter::kTeecValueFieldNumber;
const int TeecParameter::kPlaceHolderFieldNumber;
#endif  // !_MSC_VER

TeecParameter::TeecParameter()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter)
}

void TeecParameter::InitAsDefaultInstance() {
  teecsharedmemoryreference_ = const_cast< ::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecSharedMemoryReference*>(&::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecSharedMemoryReference::default_instance());
  teecvalue_ = const_cast< ::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecValue*>(&::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecValue::default_instance());
}

TeecParameter::TeecParameter(const TeecParameter& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter)
}

void TeecParameter::SharedCtor() {
  _cached_size_ = 0;
  type_ = 1;
  teecsharedmemoryreference_ = NULL;
  teecvalue_ = NULL;
  placeholder_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TeecParameter::~TeecParameter() {
  // @@protoc_insertion_point(destructor:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter)
  SharedDtor();
}

void TeecParameter::SharedDtor() {
  if (this != default_instance_) {
    delete teecsharedmemoryreference_;
    delete teecvalue_;
  }
}

void TeecParameter::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TeecParameter::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TeecParameter_descriptor_;
}

const TeecParameter& TeecParameter::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GPDataTypes_2eproto();
  return *default_instance_;
}

TeecParameter* TeecParameter::default_instance_ = NULL;

TeecParameter* TeecParameter::New() const {
  return new TeecParameter;
}

void TeecParameter::Clear() {
  if (_has_bits_[0 / 32] & 15) {
    type_ = 1;
    if (has_teecsharedmemoryreference()) {
      if (teecsharedmemoryreference_ != NULL) teecsharedmemoryreference_->::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecSharedMemoryReference::Clear();
    }
    if (has_teecvalue()) {
      if (teecvalue_ != NULL) teecvalue_->::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecValue::Clear();
    }
    placeholder_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TeecParameter::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter.Type type = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecParameter_Type_IsValid(value)) {
            set_type(static_cast< ::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecParameter_Type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_teecSharedMemoryReference;
        break;
      }

      // optional .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference teecSharedMemoryReference = 2;
      case 2: {
        if (tag == 18) {
         parse_teecSharedMemoryReference:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_teecsharedmemoryreference()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_teecValue;
        break;
      }

      // optional .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue teecValue = 3;
      case 3: {
        if (tag == 26) {
         parse_teecValue:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_teecvalue()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_placeHolder;
        break;
      }

      // optional int32 placeHolder = 4;
      case 4: {
        if (tag == 32) {
         parse_placeHolder:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &placeholder_)));
          set_has_placeholder();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter)
  return false;
#undef DO_
}

void TeecParameter::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter)
  // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter.Type type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // optional .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference teecSharedMemoryReference = 2;
  if (has_teecsharedmemoryreference()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->teecsharedmemoryreference(), output);
  }

  // optional .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue teecValue = 3;
  if (has_teecvalue()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->teecvalue(), output);
  }

  // optional int32 placeHolder = 4;
  if (has_placeholder()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->placeholder(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter)
}

::google::protobuf::uint8* TeecParameter::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter)
  // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter.Type type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // optional .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference teecSharedMemoryReference = 2;
  if (has_teecsharedmemoryreference()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->teecsharedmemoryreference(), target);
  }

  // optional .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue teecValue = 3;
  if (has_teecvalue()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->teecvalue(), target);
  }

  // optional int32 placeHolder = 4;
  if (has_placeholder()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->placeholder(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter)
  return target;
}

int TeecParameter::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecParameter.Type type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

    // optional .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference teecSharedMemoryReference = 2;
    if (has_teecsharedmemoryreference()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->teecsharedmemoryreference());
    }

    // optional .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue teecValue = 3;
    if (has_teecvalue()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->teecvalue());
    }

    // optional int32 placeHolder = 4;
    if (has_placeholder()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->placeholder());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TeecParameter::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TeecParameter* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TeecParameter*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TeecParameter::MergeFrom(const TeecParameter& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_teecsharedmemoryreference()) {
      mutable_teecsharedmemoryreference()->::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecSharedMemoryReference::MergeFrom(from.teecsharedmemoryreference());
    }
    if (from.has_teecvalue()) {
      mutable_teecvalue()->::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecValue::MergeFrom(from.teecvalue());
    }
    if (from.has_placeholder()) {
      set_placeholder(from.placeholder());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TeecParameter::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TeecParameter::CopyFrom(const TeecParameter& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TeecParameter::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_teecsharedmemoryreference()) {
    if (!this->teecsharedmemoryreference().IsInitialized()) return false;
  }
  if (has_teecvalue()) {
    if (!this->teecvalue().IsInitialized()) return false;
  }
  return true;
}

void TeecParameter::Swap(TeecParameter* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(teecsharedmemoryreference_, other->teecsharedmemoryreference_);
    std::swap(teecvalue_, other->teecvalue_);
    std::swap(placeholder_, other->placeholder_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TeecParameter::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TeecParameter_descriptor_;
  metadata.reflection = TeecParameter_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TeecSharedMemory::kMBufferFieldNumber;
const int TeecSharedMemory::kMFlagFieldNumber;
const int TeecSharedMemory::kSizeFieldNumber;
const int TeecSharedMemory::kMReturnSizeFieldNumber;
const int TeecSharedMemory::kMIDFieldNumber;
#endif  // !_MSC_VER

TeecSharedMemory::TeecSharedMemory()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemory)
}

void TeecSharedMemory::InitAsDefaultInstance() {
}

TeecSharedMemory::TeecSharedMemory(const TeecSharedMemory& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemory)
}

void TeecSharedMemory::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  mbuffer_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mflag_ = 0;
  size_ = 0;
  mreturnsize_ = 0;
  mid_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TeecSharedMemory::~TeecSharedMemory() {
  // @@protoc_insertion_point(destructor:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemory)
  SharedDtor();
}

void TeecSharedMemory::SharedDtor() {
  if (mbuffer_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete mbuffer_;
  }
  if (this != default_instance_) {
  }
}

void TeecSharedMemory::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TeecSharedMemory::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TeecSharedMemory_descriptor_;
}

const TeecSharedMemory& TeecSharedMemory::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GPDataTypes_2eproto();
  return *default_instance_;
}

TeecSharedMemory* TeecSharedMemory::default_instance_ = NULL;

TeecSharedMemory* TeecSharedMemory::New() const {
  return new TeecSharedMemory;
}

void TeecSharedMemory::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<TeecSharedMemory*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 31) {
    ZR_(mflag_, mid_);
    if (has_mbuffer()) {
      if (mbuffer_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        mbuffer_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TeecSharedMemory::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemory)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes mBuffer = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_mbuffer()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_mFlag;
        break;
      }

      // required int32 mFlag = 2;
      case 2: {
        if (tag == 16) {
         parse_mFlag:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mflag_)));
          set_has_mflag();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_size;
        break;
      }

      // required int32 size = 3;
      case 3: {
        if (tag == 24) {
         parse_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &size_)));
          set_has_size();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_mReturnSize;
        break;
      }

      // optional int32 mReturnSize = 4;
      case 4: {
        if (tag == 32) {
         parse_mReturnSize:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mreturnsize_)));
          set_has_mreturnsize();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_mID;
        break;
      }

      // optional int32 mID = 5;
      case 5: {
        if (tag == 40) {
         parse_mID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mid_)));
          set_has_mid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemory)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemory)
  return false;
#undef DO_
}

void TeecSharedMemory::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemory)
  // required bytes mBuffer = 1;
  if (has_mbuffer()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->mbuffer(), output);
  }

  // required int32 mFlag = 2;
  if (has_mflag()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->mflag(), output);
  }

  // required int32 size = 3;
  if (has_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->size(), output);
  }

  // optional int32 mReturnSize = 4;
  if (has_mreturnsize()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->mreturnsize(), output);
  }

  // optional int32 mID = 5;
  if (has_mid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->mid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemory)
}

::google::protobuf::uint8* TeecSharedMemory::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemory)
  // required bytes mBuffer = 1;
  if (has_mbuffer()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->mbuffer(), target);
  }

  // required int32 mFlag = 2;
  if (has_mflag()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->mflag(), target);
  }

  // required int32 size = 3;
  if (has_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->size(), target);
  }

  // optional int32 mReturnSize = 4;
  if (has_mreturnsize()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->mreturnsize(), target);
  }

  // optional int32 mID = 5;
  if (has_mid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->mid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemory)
  return target;
}

int TeecSharedMemory::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes mBuffer = 1;
    if (has_mbuffer()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->mbuffer());
    }

    // required int32 mFlag = 2;
    if (has_mflag()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->mflag());
    }

    // required int32 size = 3;
    if (has_size()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->size());
    }

    // optional int32 mReturnSize = 4;
    if (has_mreturnsize()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->mreturnsize());
    }

    // optional int32 mID = 5;
    if (has_mid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->mid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TeecSharedMemory::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TeecSharedMemory* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TeecSharedMemory*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TeecSharedMemory::MergeFrom(const TeecSharedMemory& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_mbuffer()) {
      set_mbuffer(from.mbuffer());
    }
    if (from.has_mflag()) {
      set_mflag(from.mflag());
    }
    if (from.has_size()) {
      set_size(from.size());
    }
    if (from.has_mreturnsize()) {
      set_mreturnsize(from.mreturnsize());
    }
    if (from.has_mid()) {
      set_mid(from.mid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TeecSharedMemory::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TeecSharedMemory::CopyFrom(const TeecSharedMemory& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TeecSharedMemory::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void TeecSharedMemory::Swap(TeecSharedMemory* other) {
  if (other != this) {
    std::swap(mbuffer_, other->mbuffer_);
    std::swap(mflag_, other->mflag_);
    std::swap(size_, other->size_);
    std::swap(mreturnsize_, other->mreturnsize_);
    std::swap(mid_, other->mid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TeecSharedMemory::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TeecSharedMemory_descriptor_;
  metadata.reflection = TeecSharedMemory_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* TeecSharedMemoryReference_Flag_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TeecSharedMemoryReference_Flag_descriptor_;
}
bool TeecSharedMemoryReference_Flag_IsValid(int value) {
  switch(value) {
    case 13:
    case 14:
    case 15:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const TeecSharedMemoryReference_Flag TeecSharedMemoryReference::TEEC_MEMREF_INPUT;
const TeecSharedMemoryReference_Flag TeecSharedMemoryReference::TEEC_MEMREF_OUTPUT;
const TeecSharedMemoryReference_Flag TeecSharedMemoryReference::TEEC_MEMREF_INOUT;
const TeecSharedMemoryReference_Flag TeecSharedMemoryReference::Flag_MIN;
const TeecSharedMemoryReference_Flag TeecSharedMemoryReference::Flag_MAX;
const int TeecSharedMemoryReference::Flag_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int TeecSharedMemoryReference::kParentFieldNumber;
const int TeecSharedMemoryReference::kMOffsetFieldNumber;
const int TeecSharedMemoryReference::kMFlagFieldNumber;
#endif  // !_MSC_VER

TeecSharedMemoryReference::TeecSharedMemoryReference()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference)
}

void TeecSharedMemoryReference::InitAsDefaultInstance() {
  parent_ = const_cast< ::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecSharedMemory*>(&::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecSharedMemory::default_instance());
}

TeecSharedMemoryReference::TeecSharedMemoryReference(const TeecSharedMemoryReference& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference)
}

void TeecSharedMemoryReference::SharedCtor() {
  _cached_size_ = 0;
  parent_ = NULL;
  moffset_ = 0;
  mflag_ = 13;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TeecSharedMemoryReference::~TeecSharedMemoryReference() {
  // @@protoc_insertion_point(destructor:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference)
  SharedDtor();
}

void TeecSharedMemoryReference::SharedDtor() {
  if (this != default_instance_) {
    delete parent_;
  }
}

void TeecSharedMemoryReference::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TeecSharedMemoryReference::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TeecSharedMemoryReference_descriptor_;
}

const TeecSharedMemoryReference& TeecSharedMemoryReference::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GPDataTypes_2eproto();
  return *default_instance_;
}

TeecSharedMemoryReference* TeecSharedMemoryReference::default_instance_ = NULL;

TeecSharedMemoryReference* TeecSharedMemoryReference::New() const {
  return new TeecSharedMemoryReference;
}

void TeecSharedMemoryReference::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_parent()) {
      if (parent_ != NULL) parent_->::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecSharedMemory::Clear();
    }
    moffset_ = 0;
    mflag_ = 13;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TeecSharedMemoryReference::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemory parent = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_parent()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_mOffset;
        break;
      }

      // required int32 mOffset = 2;
      case 2: {
        if (tag == 16) {
         parse_mOffset:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &moffset_)));
          set_has_moffset();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_mFlag;
        break;
      }

      // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference.Flag mFlag = 3;
      case 3: {
        if (tag == 24) {
         parse_mFlag:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecSharedMemoryReference_Flag_IsValid(value)) {
            set_mflag(static_cast< ::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecSharedMemoryReference_Flag >(value));
          } else {
            mutable_unknown_fields()->AddVarint(3, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference)
  return false;
#undef DO_
}

void TeecSharedMemoryReference::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference)
  // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemory parent = 1;
  if (has_parent()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->parent(), output);
  }

  // required int32 mOffset = 2;
  if (has_moffset()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->moffset(), output);
  }

  // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference.Flag mFlag = 3;
  if (has_mflag()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->mflag(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference)
}

::google::protobuf::uint8* TeecSharedMemoryReference::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference)
  // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemory parent = 1;
  if (has_parent()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->parent(), target);
  }

  // required int32 mOffset = 2;
  if (has_moffset()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->moffset(), target);
  }

  // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference.Flag mFlag = 3;
  if (has_mflag()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->mflag(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference)
  return target;
}

int TeecSharedMemoryReference::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemory parent = 1;
    if (has_parent()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->parent());
    }

    // required int32 mOffset = 2;
    if (has_moffset()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->moffset());
    }

    // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecSharedMemoryReference.Flag mFlag = 3;
    if (has_mflag()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->mflag());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TeecSharedMemoryReference::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TeecSharedMemoryReference* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TeecSharedMemoryReference*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TeecSharedMemoryReference::MergeFrom(const TeecSharedMemoryReference& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_parent()) {
      mutable_parent()->::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecSharedMemory::MergeFrom(from.parent());
    }
    if (from.has_moffset()) {
      set_moffset(from.moffset());
    }
    if (from.has_mflag()) {
      set_mflag(from.mflag());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TeecSharedMemoryReference::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TeecSharedMemoryReference::CopyFrom(const TeecSharedMemoryReference& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TeecSharedMemoryReference::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  if (has_parent()) {
    if (!this->parent().IsInitialized()) return false;
  }
  return true;
}

void TeecSharedMemoryReference::Swap(TeecSharedMemoryReference* other) {
  if (other != this) {
    std::swap(parent_, other->parent_);
    std::swap(moffset_, other->moffset_);
    std::swap(mflag_, other->mflag_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TeecSharedMemoryReference::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TeecSharedMemoryReference_descriptor_;
  metadata.reflection = TeecSharedMemoryReference_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* TeecValue_Flag_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TeecValue_Flag_descriptor_;
}
bool TeecValue_Flag_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const TeecValue_Flag TeecValue::TEEC_VALUE_INPUT;
const TeecValue_Flag TeecValue::TEEC_VALUE_OUTPUT;
const TeecValue_Flag TeecValue::TEEC_VALUE_INOUT;
const TeecValue_Flag TeecValue::Flag_MIN;
const TeecValue_Flag TeecValue::Flag_MAX;
const int TeecValue::Flag_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int TeecValue::kAFieldNumber;
const int TeecValue::kBFieldNumber;
const int TeecValue::kMFlagFieldNumber;
#endif  // !_MSC_VER

TeecValue::TeecValue()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue)
}

void TeecValue::InitAsDefaultInstance() {
}

TeecValue::TeecValue(const TeecValue& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue)
}

void TeecValue::SharedCtor() {
  _cached_size_ = 0;
  a_ = 0;
  b_ = 0;
  mflag_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TeecValue::~TeecValue() {
  // @@protoc_insertion_point(destructor:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue)
  SharedDtor();
}

void TeecValue::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TeecValue::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TeecValue::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TeecValue_descriptor_;
}

const TeecValue& TeecValue::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GPDataTypes_2eproto();
  return *default_instance_;
}

TeecValue* TeecValue::default_instance_ = NULL;

TeecValue* TeecValue::New() const {
  return new TeecValue;
}

void TeecValue::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<TeecValue*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 7) {
    ZR_(a_, b_);
    mflag_ = 1;
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TeecValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 a = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &a_)));
          set_has_a();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_b;
        break;
      }

      // required int32 b = 2;
      case 2: {
        if (tag == 16) {
         parse_b:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &b_)));
          set_has_b();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_mFlag;
        break;
      }

      // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue.Flag mFlag = 3;
      case 3: {
        if (tag == 24) {
         parse_mFlag:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecValue_Flag_IsValid(value)) {
            set_mflag(static_cast< ::fi::aalto::ssg::opentee::imps::pbdatatypes::TeecValue_Flag >(value));
          } else {
            mutable_unknown_fields()->AddVarint(3, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue)
  return false;
#undef DO_
}

void TeecValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue)
  // required int32 a = 1;
  if (has_a()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->a(), output);
  }

  // required int32 b = 2;
  if (has_b()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->b(), output);
  }

  // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue.Flag mFlag = 3;
  if (has_mflag()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->mflag(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue)
}

::google::protobuf::uint8* TeecValue::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue)
  // required int32 a = 1;
  if (has_a()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->a(), target);
  }

  // required int32 b = 2;
  if (has_b()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->b(), target);
  }

  // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue.Flag mFlag = 3;
  if (has_mflag()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->mflag(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue)
  return target;
}

int TeecValue::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 a = 1;
    if (has_a()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->a());
    }

    // required int32 b = 2;
    if (has_b()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->b());
    }

    // required .fi.aalto.ssg.opentee.imps.pbdatatypes.TeecValue.Flag mFlag = 3;
    if (has_mflag()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->mflag());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TeecValue::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TeecValue* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TeecValue*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TeecValue::MergeFrom(const TeecValue& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_a()) {
      set_a(from.a());
    }
    if (from.has_b()) {
      set_b(from.b());
    }
    if (from.has_mflag()) {
      set_mflag(from.mflag());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TeecValue::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TeecValue::CopyFrom(const TeecValue& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TeecValue::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void TeecValue::Swap(TeecValue* other) {
  if (other != this) {
    std::swap(a_, other->a_);
    std::swap(b_, other->b_);
    std::swap(mflag_, other->mflag_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TeecValue::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TeecValue_descriptor_;
  metadata.reflection = TeecValue_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pbdatatypes
}  // namespace imps
}  // namespace opentee
}  // namespace ssg
}  // namespace aalto
}  // namespace fi

// @@protoc_insertion_point(global_scope)
