/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jnix.h>
/* Header for class org_opensc_pkcs11_spi_PKCS11CipherSpi */

#ifndef _Included_org_opensc_pkcs11_spi_PKCS11CipherSpi
#define _Included_org_opensc_pkcs11_spi_PKCS11CipherSpi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensc_pkcs11_spi_PKCS11CipherSpi
 * Method:    initEncryptNative
 * Signature: (JJJJI)V
 */
JNIEXPORT void JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_spi_PKCS11CipherSpi_initEncryptNative)
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     org_opensc_pkcs11_spi_PKCS11CipherSpi
 * Method:    initDecryptNative
 * Signature: (JJJJI)V
 */
JNIEXPORT void JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_spi_PKCS11CipherSpi_initDecryptNative)
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     org_opensc_pkcs11_spi_PKCS11CipherSpi
 * Method:    updateDecryptNative
 * Signature: (JJJJ[BII)[B
 */
JNIEXPORT jbyteArray JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_spi_PKCS11CipherSpi_updateDecryptNative)
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_opensc_pkcs11_spi_PKCS11CipherSpi
 * Method:    updateEncryptNative
 * Signature: (JJJJ[BII)[B
 */
JNIEXPORT jbyteArray JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_spi_PKCS11CipherSpi_updateEncryptNative)
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_opensc_pkcs11_spi_PKCS11CipherSpi
 * Method:    updateDecryptNativeOff
 * Signature: (JJJJ[BII[BI)I
 */
JNIEXPORT jint JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_spi_PKCS11CipherSpi_updateDecryptNativeOff)
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     org_opensc_pkcs11_spi_PKCS11CipherSpi
 * Method:    updateEncryptNativeOff
 * Signature: (JJJJ[BII[BI)I
 */
JNIEXPORT jint JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_spi_PKCS11CipherSpi_updateEncryptNativeOff)
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     org_opensc_pkcs11_spi_PKCS11CipherSpi
 * Method:    doFinalDecryptNative
 * Signature: (JJJJ[BII)[B
 */
JNIEXPORT jbyteArray JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_spi_PKCS11CipherSpi_doFinalDecryptNative)
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_opensc_pkcs11_spi_PKCS11CipherSpi
 * Method:    doFinalEncryptNative
 * Signature: (JJJJ[BII)[B
 */
JNIEXPORT jbyteArray JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_spi_PKCS11CipherSpi_doFinalEncryptNative)
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_opensc_pkcs11_spi_PKCS11CipherSpi
 * Method:    doDecryptNative
 * Signature: (JJJJ[BII)[B
 */
JNIEXPORT jbyteArray JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_spi_PKCS11CipherSpi_doDecryptNative)
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_opensc_pkcs11_spi_PKCS11CipherSpi
 * Method:    doEncryptNative
 * Signature: (JJJJ[BII)[B
 */
JNIEXPORT jbyteArray JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_spi_PKCS11CipherSpi_doEncryptNative)
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_opensc_pkcs11_spi_PKCS11CipherSpi
 * Method:    doFinalDecryptNativeOff
 * Signature: (JJJJ[BII[BI)I
 */
JNIEXPORT jint JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_spi_PKCS11CipherSpi_doFinalDecryptNativeOff)
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     org_opensc_pkcs11_spi_PKCS11CipherSpi
 * Method:    doFinalEncryptNativeOff
 * Signature: (JJJJ[BII[BI)I
 */
JNIEXPORT jint JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_spi_PKCS11CipherSpi_doFinalEncryptNativeOff)
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     org_opensc_pkcs11_spi_PKCS11CipherSpi
 * Method:    doDecryptNativeOff
 * Signature: (JJJJ[BII[BI)I
 */
JNIEXPORT jint JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_spi_PKCS11CipherSpi_doDecryptNativeOff)
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     org_opensc_pkcs11_spi_PKCS11CipherSpi
 * Method:    doEncryptNativeOff
 * Signature: (JJJJ[BII[BI)I
 */
JNIEXPORT jint JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_spi_PKCS11CipherSpi_doEncryptNativeOff)
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
