/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jnix.h>
/* Header for class org_opensc_pkcs11_wrap_PKCS11KeyPairGenerator */

#ifndef _Included_org_opensc_pkcs11_wrap_PKCS11KeyPairGenerator
#define _Included_org_opensc_pkcs11_wrap_PKCS11KeyPairGenerator
#ifdef __cplusplus
extern "C" {
#endif
#undef org_opensc_pkcs11_wrap_PKCS11KeyPairGenerator_N_STATIC_PRIVATE_ATTRIBUTES
#define org_opensc_pkcs11_wrap_PKCS11KeyPairGenerator_N_STATIC_PRIVATE_ATTRIBUTES 9L
#undef org_opensc_pkcs11_wrap_PKCS11KeyPairGenerator_N_STATIC_PUBLIC_ATTRIBUTES
#define org_opensc_pkcs11_wrap_PKCS11KeyPairGenerator_N_STATIC_PUBLIC_ATTRIBUTES 4L
/*
 * Class:     org_opensc_pkcs11_wrap_PKCS11KeyPairGenerator
 * Method:    generateKeyPairNative
 * Signature: (JJJI[Lorg/opensc/pkcs11/wrap/PKCS11Attribute;[Lorg/opensc/pkcs11/wrap/PKCS11Attribute;)[J
 */
JNIEXPORT jlongArray JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_wrap_PKCS11KeyPairGenerator_generateKeyPairNative)
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
